dues_monthly_goal: 2000
dues_total_goal: 7500
obligations:
  "Czynsz (Zielona 30 l.u. 3)":
    amount_pln: 973.50
    every_months: 1
  Księgowość:
    amount_pln: 25.0
    every_months: 1
  "Domeny (hs-ldz.pl, hakierspejs.pl)":
    amount_pln: 104.79
    every_months: 12
  "Podatek od nieruchomości (orientacyjnie)":
    amount_pln: 1200
    every_months: 12
  Internet Toya 100mbps:
    amount_pln: 67.65
    every_months: 1
  "Meetup (73.73 USD \xB1 kurs)":
    amount_pln: 290.0
    every_months: 6
  "Pr\u0105d (150% \u015Br. op\u0142., zaokr.)":
    amount_pln: 600
    every_months: 1
  "Hosting w HSWAW":
    amount_pln: 128
    every_months: 1
obligations_reserve_months: 3
reservations:
  "Wyr\xF3wnanie ze starym stanem":
    amount_pln: 327.83
  "Dodatkowe 600 PLN rezerwacji wg spotorgu z 23 kwietnia 2024r":
    amount_pln: 600.00
