dues_monthly_goal: 2000
dues_total_goal: 7500
obligations:
  "Czynsz (Zielona 30 l.u. 3)":
    amount_pln: 1273.87
    every_months: 1
  Księgowość:
    amount_pln: 150.0
    every_months: 1
  "Domeny (hs-ldz.pl, hakierspejs.pl)":
    amount_pln: 140
    every_months: 12
  "Podatek od nieruchomości (orientacyjnie)":
    amount_pln: 1512
    every_months: 12
  Internet Toya 1000mbps:
    amount_pln: 100.86
    every_months: 1
  "Meetup (130 USD \xB1 kurs wg ost. trans.)":
    amount_pln: 519.73
    every_months: 6
  "Pr\u0105d (150% \u015Br. op\u0142., zaokr.)":
    amount_pln: 823.5
    every_months: 1
  "Hosting w HSWAW (VM 8CPU/16G/200G)":
    amount_pln: 128
    every_months: 1
obligations_reserve_months: 6
reservations:
  "Wyr\xF3wnanie ze starym stanem":
    amount_pln: 327.83
  "Rezerwacja na ogrzewanie":
    amount_pln: 3800
